export enum Errors {
    JOB_NOT_FOUND = 'JOB_NOT_FOUND',
    BLOCK_NUMBER_DOES_NOT_SET = 'BLOCK_NUMBER_DOES_NOT_SET',
    UNDEFINED_SUBGRAPH_LATEST_BLOCK_NUMBER = 'UNDEFINED_SUBGRAPH_LATEST_BLOCK_NUMBER',
}
