export enum Errors {
    STOREFRONT_WITH_SLUG_EXISTS = 'STOREFRONT_WITH_SLUG_EXISTS',
    SLUG_IS_REQUIRED = 'SLUG_IS_REQUIRED',
    LOGO_IS_REQUIRED = 'LOGO_IS_REQUIRED',
    WRONG_COLLECTIONS_DATA = 'WRONG_COLLECTIONS_DATA',
    WRONG_CARDS_DATA = 'WRONG_CARDS_DATA',
    STORE_FRONT_PAGES_EMPTY = 'STORE_FRONT_PAGES_EMPTY',
    STORE_FRONT_CARDS_EMPTY = 'STORE_FRONT_CARDS_EMPTY',
    STORE_FRONT_COLLECTIONS_EMPTY = 'STORE_FRONT_COLLECTIONS_EMPTY',
}
