export enum Errors {
    IMAGE_FILE_REQUIRED = 'IMAGE_FILE_REQUIRED',
    METADATA_EXISTS = 'METADATA_EXISTS',
    WRONG_SYMBOL = 'WRONG_SYMBOL',
    WRONG_VALUE = 'WRONG_VALUE',
    CAN_NOT_GET_NEXT_TOKEN_IDENTIFIER = 'CAN_NOT_GET_NEXT_TOKEN_IDENTIFIER',
    TOKEN_METADATA_DOES_NOT_CREATED = 'TOKEN_METADATA_DOES_NOT_CREATED',
    CAN_NOT_STORE_IMAGE_METADATA = 'CAN_NOT_STORE_IMAGE_METADATA',
    CAN_NOT_STORE_ANIMATION_METADATA = 'CAN_NOT_STORE_ANIMATION_METADATA',
}
